- name: Define User Project Name
  set_fact:
    user_project: 'user{{ item }}-project'

- name: Evaluate Camel K Subscription
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'camelk_subscription.yml.j2') }}"
