# - name: Check if codeready was uninstalled
#   k8s:
#     api_key: '{{ token }}'
#     host: '{{ server }}'
#     validate_certs: '{{ verify_tls }}'
#     state: absent
#     wait: true
#     api_version: org.eclipse.che/v1
#     kind: CheCluster
#     name: codeready-workspaces
#     namespace: '{{ workshop_che_namespace }}'

- name: Delete CodeReady project
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: absent
    wait: true
    kind: Project
    api_version: project.openshift.io/v1
    name: '{{ workshop_che_namespace }}'

- name: Delete {{ solution_explorer_namespace }} project
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: absent
    wait: true
    kind: Project
    api_version: project.openshift.io/v1
    name: '{{ solution_explorer_namespace }}'


- name: Delete Users projects
  with_sequence: start=1 end={{ participants }}
  when:
    - participants|int > 0
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: absent
    wait: true
    kind: Project
    api_version: project.openshift.io/v1
    name: 'user{{ item }}-project'
