- name: create project for {{ t_user }}
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    kind: Project
    api_version: project.openshift.io/v1
    definition:
      metadata:
        name: "{{ t_project_name }}"
        annotations:
          openshift.io/description: ""
          openshift.io/display-name: "Fuse Workshop project for {{ t_user }}"

- name: assign permissions for user {{ t_user }}
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    kind: RoleBinding
    api_version: rbac.authorization.k8s.io/v1
    definition:
      metadata:
        name: admin
        namespace: "{{ t_project_name }}"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: admin
      subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: "{{ t_user }}"
