- hosts: localhost
  name: Install Camel K Workshop
  vars:
    delete_workshop: false
    verify_tls: no
    ocp_username: opentlc-mgr
    debug_enable: false
    insecure_skip_tls_verify: true
    # CHE configuration
    workshop_rhsso_admin_user_name: admin
    workshop_rhsso_admin_password: admin
    workshop_openshift_user_password: openshift
    workshop_admin_password: admin_openshift
    workshop_che_user_password: openshift
    workshop_che_namespace: workshop-codeready
    # provision_webapp
    solution_explorer_client_id: tutorial-web-app
    solution_explorer_image_tag: '1.0.10'
    solution_explorer_image: 'quay.io/gcamposo/tutorial-web-app:{{ solution_explorer_image_tag }}'
    solution_explorer_namespace: "workshop-solution-explorer"
    solution_explorer_walkthrough_locations:
      - 'https://github.com/GuilhermeCamposo/workshop_camel-k'
  tasks:

    - name: Check Required Parameters
      fail: msg="This play requires 'server' and 'token' to be defined"
      when:
        - server is not defined
        - token is not defined

    - name: Define domain
      set_fact:
        domain : "{{ server | regex_replace('https://api.') | regex_replace(':6443') }}"

    - name: Set Subdomain
      set_fact:
        route_subdomain: "apps.{{ domain }}"

    - name: Set console_url
      set_fact:
        console_url: "https://console-openshift-console.{{ route_subdomain }}"

    - name: Include Solution Explorer Role
      include_role:
        name: solution-explorer
      when: not delete_workshop

    - name: Include Username Distribution
      when:
        - num_users | int > 0
        - not delete_workshop
      include_role:
        name: username-distribution

    # - name: Provision CodeReady Workspaces
    #   include_role:
    #     name: codeready
    #   when: not delete_workshop
    #
    # - name: Provision AMQ Broker Operator
    #   include_role:
    #     name: amq
    #   with_sequence: start=1 end={{ num_users }}
    #   when:
    #     - num_users|int > 0
    #     - not delete_workshop
    #
    # - name: Provision Camel K Operator
    #   with_sequence: start=1 end={{ num_users }}
    #   when:
    #     - num_users|int > 0
    #     - not delete_workshop
    #   include_role:
    #     name: camel-k
    #
    - name: Installation Finished
      when:
        - num_users|int > 0
        - not delete_workshop
      debug:
        msg: "Installation finished succesfully. User Distribution URL: https://{{ user_distribution_url }}. The password for every user is: {{ workshop_openshift_user_password }} "

    - name: Delete Workshop
      include_role:
        name: delete
      when: delete_workshop|bool
